### ISSUE TITLE
Add vars/komodoTest.groovy

### ISSUE THREAD

**Issue by dotfloat** [equinor/komodo#132]
This is a Jenkins pipeline which will:
1. Check if `${sha1}` is set. If it is, then it's PR and not komodo integration test.
2. Checkout desired repository
3. Use `komodoenv` to create a virtualenv
4. Source `ci/jenkins/testkomodo.sh`
    1. Run either `test_pr` or `test_integration`

Optionally, determine if `test_requirements.txt` exists, pip install it. Or install pytest / tox. Or whatever.

**Comment by sondreso** [comment]
Should run with f_scout_ci user (label scout_ci)

**Comment by lars-petter-hauge** [comment]
In the case that is a PR, it would be necessary for the script to run e.g. `run_install`.

Instead of forcing the need to keep a `test_requirements.txt`, the users could install their own dependencies (for instance in the `run_install`).

**Comment by dotfloat** [comment]
The idea is that the `testkomodo.sh` needs to be as small as physically possible. They'll be able to install dependencies, but they shouldn't need to. The script can check:
1. Does `test_requirements.txt` exist? Install it.
2. Is tox used? Do something smart with it.
3. Install `pytest` because we're likely going to be using it.

Before running the repo's `run_tests` script, which may also install additional things.

The idea here is that it's highly likely that the `testkomodo.sh` will be largely unmaintained, and so it needs to have as little logic as possible. In fact, I'd argue that `testkomodo.sh` can be made empty in most cases and that Jenkins will be able to figure out what to do. Ie: does `run_tests` bash function exist? No? Okay, then we'll just delete everything but `tests` and run `pytest`.

**Comment by lars-petter-hauge** [comment]
I don't know.. this sounds like the pipeline we are going to make has to do a lot of checking for various hints, and behave differently depending on the results.

The solver for `1.` might suddenly need to check for `requirements_test.txt` or `dev-requirements.txt` as well. If `2.` is solved by checking for a `tox.ini`, and the repo for some reason doesn't use tox (they just kept on laying around), that would fail as well.

Do we start parsing the `travis.yml`? (I hope that is obvious we shouldn't)

There are so many assumptions everywhere, and things go wrong there as well. I like to be explicit instead.

>The idea is that the testkomodo.sh needs to be as small as physically possible.

I get that, but I think that even with all the hint checking that we do, it wouldn't take long before it starts to break and that every repo needs to include a little bit each. And then they don't know what _they_ need to include..

I for sure don't want to be the one writing whatever is going to do all of that testing :P

But we don't need multiple function of course, it could just be a single run functions.

**Comment by dotfloat** [comment]
My concern is that not being smart means that it will be entirely RM's job to fix these things, with days wasted due to releases being deployed with broken `testkomodo.sh`s. Checking for `test_requirements.txt` is easy and installing it is most likely what the user wants. Checking for `these_are_the_packages_that_i_want_for_tests.exe` isn't. Parsing `.travis.yml` would be a great idea if our testing aligned with it, but it does not (barring the massive complexity of parsing it of course).

Again, checking for test requirements is quick and dirty and may save a future RM's day.

**Comment by lars-petter-hauge** [comment]
I disagree, I think the RM's could end up with just as much work with this in place. In the case where the `testkomodo.sh` doesn't run, they would have to start debugging our script that does lots of checking for various filenames, instead of heading straight for the `testkomodo.sh`. Also, if the responsibility of setting up the test is given to the external repo's, it is the maintainers of those repo's responsibility to fix `testkomodo.sh`, not ours to make sure we've double checked for any files/packages that perhaps should have been installed.

The RM (or anyone helping) would then post the error message to the maintainers of the external repo's, and they will have to update their `testkomodo.sh`.

I think part 1-3 are the most important points, and then the repository maintainers can start out with having an environment ready for use!

**Comment by dotfloat** [comment]
I'll concede that it might be best to have `testkomodo.sh` files be the workhorses for at least the initial release. We can review it at a later time when we've gotten more experience with it.

I'll answer your post in #133 here so as to untangle the threads. This issue is about what capabilities such a Jenkins job should have, while #133 is about whether we should have this `testkomodo.sh` file in `komodo-releases` or in each external repository.

> I have to say, the arguments you have in this issue kind of contradicts the arguments you post in #132, where it seems you argue for having komodo on its own figure out what to install and whether it is to run tox or pytest.
> 
> > This is a non-issue if the testkomodo.sh is present in the repo, and the commit that changed from pytest to tox also includes the change in testkomodo.sh.
> 
> This I agree, and therefore i also want the testkomodo.sh to initiate the testing. If komodo is supposed to do some clever thinking on it's own, as suggested in #132, I think we'll quickly end up in a place where that fails and it really doesn't help us much. Sorry for dragging in the other issue, but they're starting to correlate.

First of all I'll note that I'm not saying whose responsibility it is to figure whether to install `tox` or `pytest`. It is an example where the test configuration has changed and is a different topic to what is discussed here (which is why there are two issues).

My argument here isn't that `komodo` should have the sole responsibility of determining dependencies, but that it can have a best-guess based on files that exist, before leaving the rest to `testkomodo.sh`. If komodo is a python package distribution system, then it makes sense that all Equinor packages should have as simple and straightforward testing procedure, eg using `pytest`. Thus, by having `komodo` do some checking prior to executing `testkomodo.sh`, it'll allow that file to be empty, and allow Travis and Jenkins to share configuration, ie using `test_requirements.txt`.

The reason for this argument is that we can't assume that repository maintainers will even know about what `testkomodo.sh` even is after some time, and if they add a dependency to `.travis.yml` then it won't be noticed until the RM has to deal with it.

**Comment by sondreso** [comment]
Closed by https://github.com/equinor/komodo/pull/137
