### ISSUE TITLE
Prevent too many HM tutorial runs

### ISSUE THREAD

**Issue by jondequinor** [equinor/komodo#143]
We want to minimize the amount of HM testing that is done; maybe we elect target platforms like RHEL7 and both python versions, then only run HM tutorial for these targets.

Maybe we add a filter in the HM tutorial job that filters out non-critical releases.

Part of https://github.com/equinor/scout/issues/246

**Comment by sondreso** [comment]
Not really an issue anymore since we only have one release in the matrix. Reopen if this becomes an issue in the future
