### ISSUE TITLE
disable_komodo does not reset environment properly

### ISSUE THREAD

**Issue by sondreso** [equinor/komodo#157]
After the recent komodo update disable komodo_does not work properly (most critical is the fact that `LD_LIBRARY_PATH` is not reset properly) 
```bash
$ env > env-dump.txt
$ source /prog/res/komodo/bleeding-py36-rhel7/enable
(bleeding-py36-rhel7) $ disable_komodo
$ env | diff env-dump.txt -
```
gives
```diff
0a1
> MANPATH=/prog/res/komodo/bleeding-py36-rhel7/root/share/man:
4a6
> _PRE_KOMODO_LD_LIBRARY_PATH=
16a19
> LD_LIBRARY_PATH=/prog/res/komodo/bleeding-py36-rhel7/root/lib:/prog/res/komodo/bleeding-py36-rhel7/root/lib64
23a27
> PS1=[\u@\h \W]\$ 
28a33
> _PRE_KOMODO_MANPATH=
```

It seems that the current stable (2020.09.00) does not work perfect either, but at least it resets `LD_LIBRARY_PATH`
```bash
$ env > env-dump.txt
$ source /prog/res/komodo/stable/enable
(2020.09.00-py36) $ disable_komodo
$ env | diff env-dump.txt -
```
gives
```diff
0a1
> MANPATH=/prog/res/komodo/2020.09.00-py36/root/share/man:
4a6
> _PRE_KOMODO_LD_LIBRARY_PATH=
23a26
> PS1=[\u@\h \W]\$ 
28a32
> _PRE_KOMODO_MANPATH=
```

**Comment by markusdregi** [comment]
This should be prioritised! 👍 Perhaps we should write an integration test that could have picked this up?

**Comment by dotfloat** [comment]
Solution for bash: https://stackoverflow.com/a/39296723

The problem occurs when `LD_LIBRARY_PATH` is unset/empty. In this case following line sets `_PRE_KOMODO_LD_LIBRARY_PATH` with an empty string.
https://github.com/equinor/komodo/blob/d803ee367e9d5cdfd69c2e6e31341ab9a01f36ee/komodo/data/enable.in#L59

Then, to disable, we do:
https://github.com/equinor/komodo/blob/d803ee367e9d5cdfd69c2e6e31341ab9a01f36ee/komodo/data/enable.in#L21
... which checks if this variable is non-empty. We should use `if [[ -v _PRE_KOMODO_LD_LIBRARY_PATH ]];` to check if this variable is set.
