### ISSUE TITLE
Double Komodo release in csh prompt

### ISSUE THREAD

**Issue by markusdregi** [equinor/komodo#181]
When sourcing `komodo/stable` in a cshell I get the following prompt:

> [2020.11.00-py36] [2020.11.00-py36-rhel7] [mfane@rgsnode ~] $

while in bash I get

> (2020.11.00-py36) [mfane@rgsnode ~] $

Should we unify?

**Comment by dotfloat** [comment]
This is a bug, yes. I have provided a fix but unsure if it fixes stuff. It also seems odd to me that we are setting `KOMODO_RELEASE` at all in the `generic` -> `rhel7` redirect enable script...
