### ISSUE TITLE
Allow packages in bleeding to deploy latest (pre) release instead of master

### ISSUE THREAD

**Issue by sondreso** [equinor/komodo#190]
@sondreso commented on [Thu Jan 28 2021](https://github.com/equinor/komodo-releases/issues/1121)

Using --pre with pip allows you to install latest release including pre releases (https://pip.pypa.io/en/stable/reference/pip_install/#install-pre). 

Think it would make sense to allow this option in bleeding in addition to master

**Comment by markusdregi** [comment]
Did you not do some experimentation here @sondreso? Would perhaps be good to add that information to the issue?

**Comment by sondreso** [comment]
We can install a pre version like this: 
```bash
pip install equinor-libres==8.* --pre
Collecting equinor-libres==8.*
  Downloading equinor_libres-8.1.0rc0-cp38-cp38-macosx_10_9_x86_64.whl (851 kB)
```

The problem is that we download the package at one point in the process and then install them at a later point. (And we sort of need to know the version between these two steps) The best scenario would be to find the newest pre release prior to all of this, and then use that version as normal in the rest of the workflow.

**Comment by markusdregi** [comment]
But installing `8.*` is all good. Is the `--pre` that causes issues then? 🤔

**Comment by sondreso** [comment]
It's probably not going to cause issues, but we will have to add `--pre ` to this line: 
https://github.com/equinor/komodo/blob/c98e982fd47d56220b5fd40f73d0bb8ca5e0ab43/komodo/fetch.py#L134
Which means it will affect **all** packages.

**Comment by jondequinor** [comment]
I think parsing and grabbing the latest item from  `pip install equinor-libres== --use-deprecated=legacy-resolver` is the way to go.

That pip "api" is most likely to be introduced to the new resolver as well.

Benefits are that you'll always get the latest release, so you don't have to bump bleeding for each new major libres release.
