### ISSUE TITLE
Automatic PR for upgrade-proposals

### ISSUE THREAD

**Issue by mortalisk** [equinor/komodo#200]
A release manager should be able to initiate a simple job to copy upgrade proposals and merge into an existing release and write the results to a new release file, and then create a PR with the results.

Resolved by #198

**Comment by mortalisk** [comment]
This is blocked because squash merges are not allowed on equinor/komodo-releases

**Comment by frode-aarstad** [comment]
Add paragraph on how to use this new magic button in https://github.com/equinor/scout/blob/master/release-process/README.md then :rocket:
