### ISSUE TITLE
Make matrix configurable 

### ISSUE THREAD

**Issue by sondreso** [equinor/komodo#220]
Currently, the matrix that komodo builds is hardcoded here: 

https://github.com/equinor/komodo/blob/af96af1e1d3740699ee4c43cc00bd1784b972cc8/komodo/matrix.py#L7-L8

We should make these options configurable, such that matrixes can be configured in release repositories instead of in the main tool.

**Comment by jondequinor** [comment]
The main problem (back in the old days when I was mucking around with this) is propagating it to Jenkins. Because matrices in Jenkins are not configurable (at least they weren't).

**Comment by sondreso** [comment]
Makes sense! I guess we could circumvent the problem by using loops in Jenkins and start the build jobs with `wait: false`, now that testing is done per release?

**Comment by jondequinor** [comment]
Probably…

**Comment by kwinkunks** [comment]
This is being taken care of as #308
