### ISSUE TITLE
testKomodo: `GIT_CODE_REF` ignored

### ISSUE THREAD

**Issue by pinkwah** [equinor/komodo#221]
By default, `GIT_CODE_REF` is set to `master`, but isn't used because:
1. **Pull request**: The branch is the pull request
2. **Komodo release**: The branch name is whatever is written in the komodo release manifest file. (eg. `/prog/res/komodo/2020.01.00-py36/2020.01.00-py36`)

We should change it so that it defaults to an empty string or `null`, and if set will override the automatic version detection. This is useful for testing the job itself.

**Comment by berland** [comment]
Jenkins-specific. Closing.
