### ISSUE TITLE
Refactor to use a different rename

### ISSUE THREAD

**Issue by berland** [equinor/komodo#274]
When on Ubuntu 22.04, the `rename.ul` command is no longer available. See
https://unix.stackexchange.com/questions/716806/could-you-suggest-how-to-use-rename-ul-under-ubuntu-22-04-many-thanks

https://github.com/equinor/komodo/blob/1852315c1b80ff8b61996ad249c37a568adc4fc5/tests/test_cli.py#L57

**Comment by berland** [comment]
It might be a temporary removal, as the Debian technical committee has decided to reintroduce `rename.ul`: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003653

It does seem from the discussion that the util-linux rename is inferior to the perl-rename in terms of feature, and the perl-rename is more likely to be able to cling on to `/usr/bin/rename` in the future on Debian. This could lead us into refactoring Komodo to use the perl-rename.

On-prem Redhat 7 and Azure nodes have `/usr/bin/rename` pointing to the `util-linux` rename, and does not seem to ship the perl-rename. This adds a hurdle to porting komodo to perl-rename.

Suggest to to pin komodo to not use Ubuntu 22.04 for now, until `rename.ul` reemerges.

**Comment by berland** [comment]
Pinning done in #275

**Comment by hnformentin** [comment]
Hei, do you have a PR to link to this issue? Otherwise I am not sure why it is ready for review 🤔

**Comment by berland** [comment]
The usage of  `rename`-ul in `cli.py `seems simple, this should be refactored to use Python directly.

**Comment by berland** [comment]
A simple 
```
#!/usr/bin/python3

import sys
import os

for fn in sys.argv[3:]:
    os.rename(fn, fn.replace(sys.argv[1], sys.argv[2]))
```
is enough to have tests passing on Ubuntu 22.04
