### ISSUE TITLE
Modernize the build process

### ISSUE THREAD

**Issue by kwinkunks** [equinor/komodo#296]
The build is not too complicated and should be quite easy to move to PEP621-style building with `pyproject.toml`. This would also allow us to gather all the build tool setup in one place, getting rid of `.isort.cfg`, for example.

**Comment by kwinkunks** [comment]
**Blocked** by lack of support for `flake8` options in `pyproject.toml`.

Question for @berland &mdash; do we _need_ `flake8` as well as `pylint`? I don't know what it does that `pylint` does not. 

Note: we can set `max-line-length = 88` in `pylint` as well.

Backstory for lack of support: https://github.com/john-hen/Flake8-pyproject

**Comment by berland** [comment]
I have typically used flake8 as a poor-mans pylint, it is very much faster than pylint, and its issues are typically easier to fix than pylint's. So my procedure when styling repos is usually to first get it to pass flake8, then start pylinting.

Also, pylint is usually loaded with disables, while flake8 we can run without any. 

How many real cases where flake8 would complains about and pylint (with enable=all) is silent I don't really know.

**Comment by berland** [comment]
We can use  `flake8 --max-line-length 88` directly in `style.yml` in order to avoid having it configured in `setup.cfg`

**Comment by berland** [comment]
An example is https://github.com/equinor/everest. Here pylint is enabled in ci, but stripped down to epsilon (?) through disables. Flake8 on this repo does not pass (and is not in CI), and I would start by flake'ing the code before more linting.
