### ISSUE TITLE
Refactor test fixtures into conftest.py

### ISSUE THREAD

**Issue by kwinkunks** [equinor/komodo#303]
Some tests (currently `test_build.py` and `test_fetch.py` but also `test_show_version.py` in the unmerged `cli-get-version` branch) use fixtures, but these are defined in the test files. Best practice to enable sharing them between tests is to put them all in `conftest.py`.

**Comment by kwinkunks** [comment]
Have done this in `cli-get-version` but not in `test_build.py` and `test_fetch.py` because I can't see how to do it when each test file has its own context to mock. :thinking:

**Comment by jonathan-eq** [comment]
It is a monkeypatch, so you can mock both of them. They are completely independent, so it should be fine.
