### ISSUE TITLE
Hidden copy of release directory is never removed

### ISSUE THREAD

**Issue by kwinkunks** [equinor/komodo#326]
A hidden (dot), redundant copy of the release directory (containing the `enable` script and the `root` directory) is created but never removed:

https://github.com/equinor/komodo/blob/main/komodo/cli.py#L118-L133

There's quite a dance going on here, I think it can be simplified.

**Comment by kwinkunks** [comment]
Trying to understand what the script currently does.

- `builds` is a directory containing various releases (usually called 'prefix')
- `builds/release` is an old release directory containing a komodo release (scripts, bin, etc)
- `release` is a new komodo release directory (that we just made and want to 'install' in `builds`)

Here's what we're doing, in a sort of shelly pseudocode, with hardcoded names instead of variables to try to make it clearer. All this is getting done with shell commands via `subprocess`.

    mv release .release
    sudo rsync -a .release builds        # <-- this .release dir never gets removed.
    
    if builds/release already exists:
        sudo mv builds/release builds/release.delete

    sudo mv builds/.release builds/release
    sudo rm -rf builds/release.delete

It seems to me that this could all be replaced with:

    mv release builds/release

If the concern is that `mv` might be interrupted, leaving things in a bad state, then maybe:

    if builds/release already exists:
        sudo mv builds/release builds/release.delete
    mv release builds/release
    rm -rf builds/release.delete

I'm skeptical that `sudo` is required for any of this.

I also wonder if it wouldn't be better to do it all in Python instead of shell. For example, here's a nice solution that is both **atomic** and works **across file systems**:

```python
import errno
import os
import shutil


def safe_move(src, dst):
    """Rename a file from ``src`` to ``dst``.

    *   Moves must be atomic.  ``shutil.move()`` is not atomic.
        Note that multiple threads may try to write to the cache at once,
        so atomicity is required to ensure the serving on one thread doesn't
        pick up a partially saved image from another thread.

    *   Moves must work across filesystems.  Often temp directories and the
        cache directories live on different filesystems.  ``os.rename()`` can
        throw errors if run across filesystems.

    So we try ``os.rename()``, but if we detect a cross-filesystem copy, we
    switch to ``shutil.move()`` with some wrappers to make it atomic.
    """
    try:
        os.rename(src, dst)
    except OSError as err:

        if err.errno == errno.EXDEV:
            # Generate a unique ID, and copy `<src>` to the target directory
            # with a temporary name `<dst>.<ID>.tmp`.  Because we're copying
            # across a filesystem boundary, this initial copy may not be
            # atomic.  We intersperse a random UUID so if different processes
            # are copying into `<dst>`, they don't overlap in their tmp copies.
            copy_id = uuid.uuid4()
            tmp_dst = "%s.%s.tmp" % (dst, copy_id)
            shutil.copyfile(src, tmp_dst)

            # Then do an atomic rename onto the new name, and clean up the
            # source image.
            os.rename(tmp_dst, dst)
            os.unlink(src)
        else:
            raise
```

Code is from [this blog post](https://alexwlchan.net/2019/atomic-cross-filesystem-moves-in-python/) and carries an MIT license.

**Comment by jonathan-eq** [comment]
After discussing this with @xjules, we decided it is not necessary. Most times, we will be running Komodo in /tmp, so cleanup will be automatic anyways.
