### ISSUE TITLE
Running komodo-clean-repository without check does not prettify yaml

### ISSUE THREAD

**Issue by eivindjahren** [equinor/komodo#354]
In 82c43a83c39f2d728613d9bf8274b848a9d9dc4f the logic of the prettifyer was changed so that running without --check does nothing:
https://github.com/equinor/komodo/blob/d9b2344f24874b11b5e7cd75fb06dbfd3d1c50f3/komodo/release_cleanup.py#L183-L188

**Comment by berland** [comment]
I assume @eivindjahren means this diff:

https://github.com/equinor/komodo/commit/82c43a83c39f2d728613d9bf8274b848a9d9dc4f#diff-
4ae31884b485560077da4798841b577a8d0dd1f16c290487f38099702216bbeb

**Comment by eivindjahren** [comment]
Yes @berland , updated it now.
