### ISSUE TITLE
Remove location support through locations.yml

### ISSUE THREAD

**Issue by berland** [equinor/komodo#364]
The location support provided by locations.yml is no longer in use from Komodo 2023.06. 

The suggestion is to remove it. If it should stay in the repository it should be refactored in a backwards incompatible change, thus the first step is to remove it, and then later reimplement on demand.

**Comment by hnformentin** [comment]
- [ ] komodo: https://github.com/equinor/komodo-releases/pull/3929
- [ ] komodo-releases:
- [ ] fmu-logging:
