### ISSUE TITLE
`make` entry of `repository.yaml` should be validated earlier

### ISSUE THREAD

**Issue by yngve-sk** [equinor/komodo#383]
Ref: https://github.com/equinor/komodo-releases/blob/fbfc58e28589628974a30b3d8feae19b637c2739/repository.yml#L17472
It should be checked that the `make` entry is valid, this currently shows up as an error a bit harder to decipher, ref: https://github.com/equinor/komodo-releases/actions/runs/6010649782/job/16303506165#step:8:1799

**Comment by jonathan-eq** [comment]
Linked to #384
