### ISSUE TITLE
create_links should tell when it is the stable link that is moved

### ISSUE THREAD

**Issue by berland** [equinor/komodo#392]
We are getting messages from create_links like this:

> Existing symlink 2023.06-py38 moved from 2023.06.10-py38 to 2023.06.11-py38

which are nice, but it would be even nicer if it also could state that "stable" is actually pointing to this, and thus stable is impliclitly moved.

**Comment by berland** [comment]
In this loop:
https://github.com/equinor/komodo/blob/3272d79922779096cc405fbbfee8810032f0b63c/komodo/symlink/create_links.py#L48-L50
the dictionary can be looked up to see whatever points to the link we are changing.

**Comment by jonathan-eq** [comment]
Related to https://github.com/equinor/komodo-releases/issues/3927

**Comment by jonathan-eq** [comment]
I think I misunderstood this issue, I will re-read the code thoroughly.

**Comment by berland** [comment]
I think we should also tell when any other symlinks (testing/unstable) are implicitly moved.

**Comment by jonathan-eq** [comment]
> I think we should also tell when any other symlinks (testing/unstable) are implicitly moved.

Does this only include those three (stable, testing, unstable), or should I list every symlink that was affected by the update?

**Comment by jonathan-eq** [comment]
tree traversal 😰
