### ISSUE TITLE
prettifier no longer writes if args.check is not given

### ISSUE THREAD

**Issue by eivindjahren** [equinor/komodo#419]
https://github.com/equinor/komodo/blob/4db287a5f319bb69af094b43bf9d784a304834cd/komodo/release_cleanup.py#L183-L185

Changed from https://github.com/equinor/komodo/blob/b5636b9ae80aac58502e86be070ff44f99932536/komodo/release_cleanup.py#L186-L188

in 82c43a83c39f2d728613d9bf8274b848a9d9dc4

**Comment by jonathan-eq** [comment]
This has already been resolved in [315fab7](https://github.com/equinor/komodo/commit/315fab7e0dc7abe6c9e47822a78cc7b164148327)
