### ISSUE TITLE
shell() does not expand bash wildcard

### ISSUE THREAD

**Issue by berland** [equinor/komodo#433]
The wildcard `*` is not expanded in these lines causing all nightly bleeding builds to be left on disk:

https://github.com/equinor/komodo/blob/6e99cc528b1a4ec2d01ee8c113822af91f85acad/komodo/cli.py#L166-L170

**Comment by berland** [comment]
We had rougly 100 bleeding builds around 5Gb each lying dormant on /prog/res/komodo ...

**Comment by andreas-el** [comment]
Relates to https://github.com/equinor/komodo-releases/issues/4983
