### ISSUE TITLE
Yaml file type validation does not work for release matrix files

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/komodo#470]
The yaml file type validation does not work for release matrix files, so a lot of the scripts crash when they encounter matrices.

**Comment by jonathan-eq** [comment]
I added the release_matrix_file in yaml_types, but some scripts are still using release_file.

**Comment by jonathan-eq** [comment]
Closing this at it is not observed in other linters.

**Comment by eivindjahren** [comment]
This should be fixed now.
