### ISSUE TITLE
komodo dependencies defined twice

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/komodo#60]
Currently `komodo` has dependencies defined both in `requirements.txt` and `setup.py`.

This is a source of errors and confusion. Move to one single source of dependency definitions.

I guess two possible solutions exist:
1) Remove `requirements.txt`.
2) `setup.py` reads the content of `requirements.txt` and use that in `install_requires`.

**Comment by markusdregi** [comment]
`komodo` should not be concerned with dependencies at all at the `requirements.txt` or `setup.py` level. The distribution file itself should be specifying versions and the repository file the dependencies of each package. Hence, I think `komodo` should be oblivious to both.
