### ISSUE TITLE
setup-py.sh downloads dependencies, potentially preventing reproducable builds

### ISSUE THREAD

**Issue by jondequinor** [equinor/komodo#61]
Through `python setup.py … install`, komodo will download anything in order to satisfy dependencies.

This means the komodo dependency graph does not need to be complete, and builds are not necessarily reproducible.

Noticed by :male_detective: @sondreso @oysteoh

**Comment by sondreso** [comment]
Closed by https://github.com/equinor/komodo-releases/pull/109 and https://github.com/equinor/komodo/pull/63
