### ISSUE TITLE
Misleading slack notification when running symlink suggester on older build

### ISSUE THREAD

**Issue by jondequinor** [equinor/komodo#91]
https://ci.equinor.com/komodo/job/komodo-suggest-symlink/128/console succeeded, and sent the following slack msg:

> Suggested new symlink (2020.02.02-py27 - unstable): (<|Open>)

The script should fail if not suggesting. Likely now it is not failing, but not suggesting (rather suggesting the empty string).

**Comment by dotfloat** [comment]
Is this still relevant? Is the issue that there was no commit made because the symlinks are the same, yet it still "suggests" a new PR?

**Comment by jondequinor** [comment]
This is still relevant. IIRC the function call that should return a PR, in some cases does not, but does not fail neither.

I think this case is reproducible for builds that pass testing, but are +2 months ahead of stable. There's a rule that says testing will only be suggested for builds +1 ahead of stable.

**Comment by berland** [comment]
Closing due to no traction and planned reimplementation in Github actions.
