### ISSUE TITLE
Symlink job doesn't play nice when there is a release for multiple pythons

### ISSUE THREAD

**Issue by pinkwah** [equinor/komodo#93]
Suppose you're releasing 2020.03.rc0 for both py27 and py36. Once both are built, there will be two PRs.

_-py27_
```diff
        "2020.02-py36": "2020.02.rc8-py36",
+       "2020.03-py27": "2020.03.rc0-py27",
        "bleeding": "bleeding-py3",
```

_-py36_
```diff
        "2020.02-py36": "2020.02.rc8-py36",
+       "2020.03-py36": "2020.03.rc0-py36",
        "bleeding": "bleeding-py3",
```
---
First you merge the py27, then try to rebase and merge py36. However, it's ambiguous for git whether it should be
```diff
        "2020.02-py36": "2020.02.rc8-py36",
        "2020.03-py27": "2020.03.rc0-py27",
+       "2020.03-py36": "2020.03.rc0-py36",
        "bleeding": "bleeding-py3",
```
...or...
```diff
        "2020.02-py36": "2020.02.rc8-py36",
-       "2020.03-py27": "2020.03.rc0-py27",
+       "2020.03-py36": "2020.03.rc0-py36",
        "bleeding": "bleeding-py3",
```
That is, it's ambiguous for git whether the user intended to add a new line or replace it because the lines are so similar.

---
I have several proposals on how to fix this:
1. Symlink job can wait until both deploys are complete before offering to rename symlinks
2. Split up the symlinks somehow so that merge conflicts don't occur
3. Wait and see if this is a problem. (I had to fight this on Monday, but it wasn't impossible to resolve manually)

**Comment by dotfloat** [comment]
Can maybe be resolved by matrix builds

**Comment by berland** [comment]
There is only one PR now for both Python versions. Closing.
