### ISSUE TITLE
When updating stable, deprecated should also be updated

### ISSUE THREAD

**Issue by dotfloat** [equinor/komodo#98]
`deprecated` points to the previous `stable` release. We should update both when symlink mode is `stable`.

**Comment by markusdregi** [comment]
This was not sufficient earlier as the compute cluster got the new stable immediately, but I support implementing this now as the cluster is currently getting the same environment as the client 👍

**Comment by dotfloat** [comment]
Decided not to update automatically. Rather, we should update deprecated a week prior to updating stable.
